INSERT ALL
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Austria', 'AT')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Belgia', 'BE')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Bułgaria', 'BG')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Chorwacja',  'HR')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Cypr', 'CY')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Czechy', 'CZ')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Dania', 'DK')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Estonia', 'EE')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Finlandia', 'FI')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Francja', 'FR')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Grecja', 'GR')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Hiszpania', 'ES')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Holandia', 'NL')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Irlandia', 'IE')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Litwa', 'LT')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Luksemburg', 'LU')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Łotwa', 'LV')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Malta', 'MT')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Niemcy', 'DE')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Polska', 'PL')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Portugalia', 'PT')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Rumunia', 'RO')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Słowacja', 'SK')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Słowenia', 'SI')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Szwecja', 'SE')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Węgry', 'HU')
INTO kody_ue (kraj_nazwa, kraj_kod) VALUES ('Włochy', 'IT')
SELECT 'Wprowadzono' FROM dual;
COMMIT;
