INSERT ALL
INTO kody_ue VALUES (1, 'Austria', 'AT')
INTO kody_ue VALUES (2, 'Belgia', 'BE')
INTO kody_ue VALUES (3, 'Bułgaria', 'BG')
INTO kody_ue VALUES (4, 'Chorwacja',  'HR')
INTO kody_ue VALUES (5, 'Cypr', 'CY')
INTO kody_ue VALUES (6, 'Czechy', 'CZ')
INTO kody_ue VALUES (7, 'Dania', 'DK')
INTO kody_ue VALUES (8, 'Estonia', 'EE')
INTO kody_ue VALUES (9, 'Finlandia', 'FI')
INTO kody_ue VALUES (10, 'Francja', 'FR')
INTO kody_ue VALUES (11, 'Grecja', 'GR')
INTO kody_ue VALUES (12, 'Hiszpania', 'ES')
INTO kody_ue VALUES (13, 'Holandia', 'NL')
INTO kody_ue VALUES (14, 'Irlandia', 'IE')
INTO kody_ue VALUES (15, 'Litwa', 'LT')
INTO kody_ue VALUES (16, 'Luksemburg', 'LU')
INTO kody_ue VALUES (17, 'Łotwa', 'LV')
INTO kody_ue VALUES (18, 'Malta', 'MT')
INTO kody_ue VALUES (19, 'Niemcy', 'DE')
INTO kody_ue VALUES (20, 'Polska', 'PL')
INTO kody_ue VALUES (21, 'Portugalia', 'PT')
INTO kody_ue VALUES (22, 'Rumunia', 'RO')
INTO kody_ue VALUES (23, 'Słowacja', 'SK')
INTO kody_ue VALUES (24, 'Słowenia', 'SI')
INTO kody_ue VALUES (25, 'Szwecja', 'SE')
INTO kody_ue VALUES (26, 'Węgry', 'HU')
INTO kody_ue VALUES (27, 'Włochy', 'IT')
SELECT 'Wprowadzono' FROM dual;
COMMIT;
/