--as SYS user
CREATE USER bank IDENTIFIED by bank;
GRANT CREATE SESSION TO bank;
ALTER USER bank quota unlimited on USERS;

GRANT CREATE ANY TABLE TO bank;
GRANT CREATE ANY VIEW TO bank;
GRANT CREATE ANY SEQUENCE TO bank;
GRANT DROP ANY TABLE TO bank;
GRANT DROP ANY VIEW TO bank;
GRANT DROP ANY SEQUENCE TO bank;
GRANT CREATE PUBLIC SYNONYM TO bank;
GRANT DROP PUBLIC SYNONYM TO bank;
GRANT CREATE TRIGGER TO bank;
